### PR TITLE
Update ro_RO.json - New Strings

### PR DESCRIPTION
**Pull request by NicuG**
I didn't added the respective emojis for the new translated strings.
Also modified 2 already translated ones.

Mulțumesc!

### CODE REVIEW

**Review by delivrance — CHANGES_REQUESTED** [review]
Hi. Please remember that you don't have to translate what the `key` says; you have to look at the source file and see what the entire string is about

**Comment by NicuG** [comment]
I know... I said that I don't added emojis (like "gift emoji" for donate, etc.), just translated the strings.

**Comment by delivrance** [comment]
What I mean is that you don't have to translate "contribute", "contributors", "donate" literally. You have to look [here](https://github.com/ytaudiobot/ytaudiobot-l10n/blob/master/messages/en_US.json#L193) for the actual strings.

**Comment by NicuG** [comment]
Check now, please.

**Pull request merged**
