### PR TITLE
3 "donate" strings translated into Catalan

### PR DESCRIPTION
**Pull request by Ecron**
Although I couldn't find the ones shown in the "Donate" dialog.

### CODE REVIEW

**Comment by delivrance** [comment]
Hi. Did you pull the changes? You can see the new strings here: https://github.com/ytaudiobot/ytaudiobot-l10n/blob/master/messages/en_US.json#L206

**Comment by Ecron** [comment]
@delivrance I can't pull the changes, only those with write access can 😅. I also translated some remaining strings. Feel free to pull 👍

**Comment by delivrance** [comment]
You can't directly [**push**](https://help.github.com/articles/github-glossary/#push) your changes to the original repo without write access, but you can [**pull**](https://help.github.com/articles/github-glossary/#pull) updates to your own fork whenever you want.

Since I've made some changes here and your fork doesn't update automatically, [**you have to do it manually**](https://help.github.com/articles/syncing-a-fork/). This is why you weren't seeing the new strings.

**Comment by delivrance** [comment]
It looks good now. Thank you!

**Comment by Ecron** [comment]
Oh, so I was using the wrong words hahaha. Thanks for the clarification :wink:

**Pull request merged**
