### PR TITLE
Update Chinese translations

### PR DESCRIPTION
**Pull request by kristar**
Update the translation of the donation and improve the original translation

### CODE REVIEW

**Review by delivrance — CHANGES_REQUESTED** [review]
Hi. There's another string you probably missed: `"donate": null,`
You can directly make changes on your branch _kristar:addChinese_ and this PR will be updated accordingly. No need to create another one.

**Comment by kristar** [comment]
I have updated it.

**Review by delivrance — CHANGES_REQUESTED** [review]
Hi Kris! Please have a look at the english file. The key is just a mean to access the whole string, you don't have to put its translation.

**Comment by kristar** [comment]
I am sorry for my negligence. I have updated it. Please check the last commit.

**Comment by delivrance** [comment]
No problems at all! ^^

**Pull request merged**
