### PR TITLE
I've completed translation.

### PR DESCRIPTION
**Pull request by ghost**
I uploaded it. What should I do next?

### CODE REVIEW

**Comment by delivrance** [comment]
Uhm... It's quite a mess. You've zipped the whole project and uploaded it in the project itself.

Please upload **ONLY** the file `Lt_uz_UZ.json` from here: https://github.com/ytaudiobot/ytaudiobot-l10n/tree/master/messages by using this button: 
image

**Comment by HusanboyBayern** [comment]
Ok!

**Comment by ghost** [comment]
Can't upload file. It's asking push request

**Comment by delivrance** [comment]
Yep, you are right. Please press the other button instead: `Create new file`
Name the new file and paste the content of Lt_uz_UZ.json there

**Comment by delivrance** [comment]
Okay, almost good! I'll move it. Hopefully you've learned a bit how github works!

**Pull request merged**
